documentation:
  - docs/*
  - assets/*
  - *.md
  
automation:
  - travis/*
  - .github/workflows/*

localization:
  - assets/store_descriptions/*/strings.xml
  - mobile/src/*/res/values-*/strings.xml
