name: Bump version and update changelog

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Bump version
        run: |
          gradle_file="mobile/build.gradle"
          
          # Get and bump version code
          currentVersionCode=$(grep 'versionCode' $gradle_file | sed -r 's/(.*) (.*)$/\2/')
          let currentVersionCode++
          
          # Remove "-release$" and and "^refs/tags/" from version name
          versionName="${GITHUB_REF%-release}"
          versionName="${GITHUB_REF##*/}"
          
          echo "Replace versionCode with $currentVersionCode"
          sed --in-place -r "s/versionCode (.*)/versionCode ${currentVersionCode}/" $gradle_file
          echo "Replace versionName with $versionName"
          sed --in-place -r "s/versionName \"(.*)\"/versionName \"${versionName}\"/" $gradle_file
          
      - name: Build store description
        run: |
          if $(echo "$GITHUB_REF" | grep -q "beta")
          then
              echo "Build store description for beta version on F-Droid"
              python3 assets/store_descriptions/generate_and_validate.py fdroidBeta
          else
              echo "Build store description for stable version on F-Droid"
              python3 assets/store_descriptions/generate_and_validate.py fdroid
          fi
          
      - name: Download release notes
        run: |
          gradle_file="mobile/build.gradle"
          currentVersionCode=$(grep 'versionCode' $gradle_file | sed -r 's/(.*) (.*)$/\2/')
          echo "Get release notes for version code $currentVersionCode"
          
          retryCount=0
          until curl https://api.github.com/repos/openhab/openhab-android/releases | jq -r '.[0].body' > fastlane/metadata/android/en-US/changelogs/${currentVersionCode}.txt
          do
              let retryCount++
              if [ "$retryCount" -gt 20 ]
              then
                  exit 1
              fi
              echo "Download failed. Retry"
              sleep 5
          done
          
          echo ""
          echo "Got release notes:"
          echo "========================"
          cat fastlane/metadata/android/en-US/changelogs/${currentVersionCode}.txt
          echo "========================"
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v6
        with:
          add: '.'
          author_name: openhab-bot
          author_email: bot@openhab.org
          message: "Bump version to $GITHUB_REF and update fastlane metadata"
          signoff: true
          branch: master
          tag: "${GITHUB_REF}-fdroid"
          token: ${{ secrets.GITHUB_TOKEN }}
