name: Validate Strings
on: push

jobs:
  app-store:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [play, playBeta, fdroid, fdroidBeta]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: python3 assets/store_descriptions/generate_and_validate.py ${{ matrix.flavor }}
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: python3 travis/validate-app-strings.py
